server:
  port: 1000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # auth-demo 路由（不需要鉴权，但网关会放行）
        - id: auth-demo-route
          uri: lb://auth-demo
          predicates:
            - Path=/auth/**

auth:
  tokenKeys:
    - Token
    - Authorization
  # 白名单
  whitelist:
    - /auth-demo/auth/login
    - /auth-demo/auth/test-token
    - /my-pass/test/get
    - /my-pass/users/register
    - /my-pass/users/login