server:
  port: 1001

spring:
  application:
    name: my-pass
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_pass?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 225599clf
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 8.x 驱动类

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml   # XML 文件位置
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true    # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印 SQL