server:
  port: 8091

spring:
  application:
    name: sqlserver-demo
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 连接 master 数据库（系统自带）
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
    username: sa
    password: your_password

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true